[platformio]
default_envs = heltec_debug

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  adafruit/Adafruit BME280 Library @ ^2.3.0
  adafruit/Adafruit Unified Sensor @ ^1.1.15
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_RUNNING_CORE=1

[env:heltec_debug]
board = heltec_wifi_lora_32_V3
build_flags =
  ${env.build_flags}
  -DVINEGUARD_RADIO_MODE=MODE_DEBUG_SERIAL_ONLY
  -DVINEGUARD_USE_MOCK_SENSORS=1
  -DENABLE_DEEP_SLEEP=0

[env:heltec_lora_p2p]
board = heltec_wifi_lora_32_V3
build_flags =
  ${env.build_flags}
  -DVINEGUARD_RADIO_MODE=MODE_LORA_P2P
  -DVINEGUARD_USE_MOCK_SENSORS=0

[env:heltec_lorawan]
board = heltec_wifi_lora_32_V3
build_flags =
  ${env.build_flags}
  -DVINEGUARD_RADIO_MODE=MODE_LORAWAN_OTAA
  -DVINEGUARD_USE_MOCK_SENSORS=0

[env:native]
platform = native
build_flags = -DUNIT_TEST

