version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: vineguard-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: vineguard-gateway
    env_file:
      - .env
    environment:
      - MQTT_HOST=mqtt
    volumes:
      - ./edge/gateway/data:/data
    depends_on:
      - mqtt
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mosquitto-data:
  mosquitto-logs:
