#!/usr/bin/env python3
"""
make_keys_header.py — Generate lorawan_keys.h from provisioning manifest.

Usage:
    python make_keys_header.py --serial VG-000001 [--manifest ../path/manifest.csv] [--show-secrets]

Output:
    firmware/esp32-node/include/lorawan_keys.h  (NEVER committed — in .gitignore)

Security:
    AppKey and NwkKey are NEVER printed to stdout unless --show-secrets is passed.
    The generated header file is .gitignore'd.
"""

import argparse
import csv
import os
import re
import sys
from pathlib import Path

MANIFEST_DEFAULT = Path(__file__).parent / "provisioning_manifest.csv"
OUTPUT_PATH = Path(__file__).parent.parent / "include" / "lorawan_keys.h"

REQUIRED_COLS = {"serial", "device_id", "dev_eui", "app_eui", "app_key", "node_type", "vineyard_id", "block_id"}
HEX_16 = re.compile(r'^[0-9A-Fa-f]{16}$')
HEX_32 = re.compile(r'^[0-9A-Fa-f]{32}$')


def err(msg: str) -> None:
    print(f"[ERROR] {msg}", file=sys.stderr)
    sys.exit(1)


def validate_hex(value: str, pattern: re.Pattern, field: str) -> str:
    v = value.strip().upper()
    if not pattern.match(v):
        err(f"Invalid {field}: '{v}' (expected {pattern.pattern})")
    return v


def hex_to_byte_array(hex_str: str) -> str:
    """Convert hex string to C byte array initialiser: { 0xAA, 0xBB, ... }"""
    pairs = [f"0x{hex_str[i:i+2]}" for i in range(0, len(hex_str), 2)]
    return "{ " + ", ".join(pairs) + " }"


def load_row(manifest_path: Path, serial: str) -> dict:
    if not manifest_path.exists():
        err(f"Manifest not found: {manifest_path}\n"
            "  Copy provisioning_manifest.example.csv → provisioning_manifest.csv and fill in real values.")

    with open(manifest_path, newline="") as f:
        reader = csv.DictReader(f)
        cols = set(reader.fieldnames or [])
        missing = REQUIRED_COLS - cols
        if missing:
            err(f"Manifest missing columns: {missing}")

        for row in reader:
            if row["serial"].strip() == serial:
                return row

    err(f"Serial '{serial}' not found in {manifest_path}")


def generate_header(row: dict, show_secrets: bool) -> str:
    serial     = row["serial"].strip()
    device_id  = row["device_id"].strip()
    dev_eui    = validate_hex(row["dev_eui"], HEX_16, "dev_eui")
    app_eui    = validate_hex(row["app_eui"], HEX_16, "app_eui")
    app_key    = validate_hex(row["app_key"], HEX_32, "app_key")
    nwk_key    = validate_hex(row.get("nwk_key", row["app_key"]), HEX_32, "nwk_key")
    node_type  = row["node_type"].strip()
    vineyard_id = row["vineyard_id"].strip()
    block_id   = row["block_id"].strip()

    if node_type not in ("basic", "precision_plus"):
        err(f"node_type must be 'basic' or 'precision_plus', got '{node_type}'")

    masked_key = "***REDACTED (use --show-secrets to display)***"

    header = f"""#pragma once
// lorawan_keys.h — AUTO-GENERATED by tools/make_keys_header.py
// DO NOT COMMIT THIS FILE.  It is listed in .gitignore.
// Node serial: {serial}
// Generated:   {__import__('datetime').datetime.utcnow().isoformat()}Z
//
// SECURITY WARNING: This file contains cryptographic keys.
// Keep it off shared filesystems, version control, and build logs.

// DevEUI (8 bytes, MSB first)
#define LORAWAN_DEV_EUI  {hex_to_byte_array(dev_eui)}

// AppEUI / JoinEUI (8 bytes, MSB first)
#define LORAWAN_APP_EUI  {hex_to_byte_array(app_eui)}

// AppKey (16 bytes, MSB first)
// {"Key value: " + hex_to_byte_array(app_key) if show_secrets else "Key omitted from comments; value in define below."}
#define LORAWAN_APP_KEY  {hex_to_byte_array(app_key)}

// NwkKey (16 bytes, MSB first) — same as AppKey for LoRaWAN 1.0 servers
#define LORAWAN_NWK_KEY  {hex_to_byte_array(nwk_key)}

// VineGuard device identity
#define DEVICE_ID        "{device_id}"
#define NODE_SERIAL      "{serial}"
#define VINEYARD_ID      "{vineyard_id}"
#define BLOCK_ID         "{block_id}"
#define NODE_TYPE        "{node_type}"
"""
    return header


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate lorawan_keys.h from provisioning manifest")
    parser.add_argument("--serial",   required=True, help="Node serial number (e.g. VG-000001)")
    parser.add_argument("--manifest", default=str(MANIFEST_DEFAULT), help="Path to provisioning CSV")
    parser.add_argument("--output",   default=str(OUTPUT_PATH),      help="Output header path")
    parser.add_argument("--show-secrets", action="store_true",
                        help="Print AppKey in stdout summary (DANGER: only for bench use)")
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    output_path   = Path(args.output)

    row = load_row(manifest_path, args.serial)
    header = generate_header(row, args.show_secrets)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(header)

    print(f"[OK] Generated: {output_path}")
    print(f"     DevEUI:    {row['dev_eui'].upper()}")
    print(f"     DeviceID:  {row['device_id']}")
    print(f"     NodeType:  {row['node_type']}")
    if not args.show_secrets:
        print("     AppKey:    (hidden — use --show-secrets to display)")


if __name__ == "__main__":
    main()
