#pragma once

#define FW_VERSION "0.2.0"

#define MODE_DEBUG_SERIAL_ONLY 1
#define MODE_LORA_P2P 2
#define MODE_LORAWAN_OTAA 3

#ifndef VINEGUARD_RADIO_MODE
#define VINEGUARD_RADIO_MODE MODE_DEBUG_SERIAL_ONLY
#endif

#ifndef VINEGUARD_USE_MOCK_SENSORS
#define VINEGUARD_USE_MOCK_SENSORS 1
#endif

#ifndef ENABLE_LEAF_WETNESS
#define ENABLE_LEAF_WETNESS 0
#endif

#ifndef ENABLE_DEEP_SLEEP
#define ENABLE_DEEP_SLEEP 1
#endif

#ifndef SAMPLE_INTERVAL_MIN
#define SAMPLE_INTERVAL_MIN 15
#endif

#ifndef TRANSMIT_INTERVAL_MIN
#define TRANSMIT_INTERVAL_MIN 15
#endif
