#include "LoRaWanClient.h"
#include <ArduinoJson.h>

static const char* TAG = "LORAWAN";

// lorawan_keys.h is generated by tools/make_keys_header.py.
// Copy lorawan_keys.example.h → lorawan_keys.h and fill in real keys.
#if defined(BUILD_MODE_LORAWAN_OTAA) && !defined(NATIVE_TEST)
  #if __has_include("../../../include/lorawan_keys.h")
    #include "../../../include/lorawan_keys.h"
  #else
    #error "include/lorawan_keys.h missing. Copy lorawan_keys.example.h and fill in your OTAA keys."
  #endif
#endif

bool LoRaWanClient::begin() {
#ifdef NATIVE_TEST
    _joined = true;
    return true;
#else
    if (!initRadio()) return false;
    return joinOTAA();
#endif
}

bool LoRaWanClient::initRadio() {
#ifdef NATIVE_TEST
    return true;
#else
    SPI.begin(PIN_LORA_SCK, PIN_LORA_MISO, PIN_LORA_MOSI, PIN_LORA_NSS);

    int16_t state = _radio.begin();
    if (state != RADIOLIB_ERR_NONE) {
        LOG_ERR(TAG, "Radio begin failed: %d", state);
        return false;
    }

    state = _radio.setTCXO(1.8f);
    if (state != RADIOLIB_ERR_NONE) {
        LOG_DBG(TAG, "TCXO returned %d (non-fatal)", state);
    }
    return true;
#endif
}

bool LoRaWanClient::joinOTAA() {
#ifdef NATIVE_TEST
    _joined = true;
    return true;
#else
    // TODO: RadioLib 6.x LoRaWAN key arrays.
    // Verify uint64_t vs uint8_t[] vs hex string format for your library version.
    // The example below uses uint8_t[] (MSB-first), which RadioLib 6.4+ accepts.
    uint8_t joinEUI[] = LORAWAN_APP_EUI;
    uint8_t devEUI[]  = LORAWAN_DEV_EUI;
    uint8_t appKey[]  = LORAWAN_APP_KEY;
    uint8_t nwkKey[]  = LORAWAN_NWK_KEY;

    // TODO: RadioLib 6.x beginOTAA signature.
    // In RadioLib 6.4.x: node.beginOTAA(joinEUI, devEUI, nwkKey, appKey, rejoin)
    // Pass false for rejoin to attempt session restore from RTC memory first.
    int16_t state = _node.beginOTAA(joinEUI, devEUI, nwkKey, appKey, false);

    if (state == RADIOLIB_ERR_NONE) {
        _joined = true;
        _rejoinCount = 0;
        LOG_INFO(TAG, "OTAA join OK");
        return true;
    }

    _rejoinCount++;
    LOG_ERR(TAG, "Join failed: %d (attempt %d/%d)", state, _rejoinCount, LORAWAN_MAX_REJOIN_ATTEMPTS);

    if (_rejoinCount >= LORAWAN_MAX_REJOIN_ATTEMPTS) {
        // Force full rejoin next time
        LOG_ERR(TAG, "Max rejoin attempts reached, clearing session");
        _rejoinCount = 0;
        // TODO: clear RTC session storage if implemented
    }
    return false;
#endif
}

bool LoRaWanClient::send(const char* jsonPayload, size_t len) {
    if (!_joined) return false;

#ifdef NATIVE_TEST
    printf("[lorawan_otaa] TX: %s\n", jsonPayload);
    return true;
#else
    uint8_t frame[VGPP_MAX_FRAME_LEN + 4];
    size_t frameLen = buildBinaryFrame(jsonPayload, frame, sizeof(frame));
    if (frameLen == 0) {
        LOG_ERR(TAG, "Binary encode failed, dropping payload");
        return false;
    }

    // TODO: RadioLib 6.x sendReceive / uplink API.
    // In RadioLib 6.4.x: node.sendReceive(data, len, port, &event)
    // Using unconfirmed uplink (no ACK) for battery efficiency.
    int16_t state = _node.sendReceive(frame, frameLen, LORAWAN_FPORT_TELEMETRY);

    if (state == RADIOLIB_ERR_NONE || state == RADIOLIB_ERR_NO_JOIN_ACCEPT) {
        LOG_INFO(TAG, "Uplink OK %zu bytes", frameLen);
        return true;
    }

    LOG_ERR(TAG, "Uplink failed: %d", state);
    if (state == RADIOLIB_ERR_NETWORK_NOT_JOINED) {
        _joined = false;  // trigger rejoin next cycle
    }
    return false;
#endif
}

// ─── Binary VGPP-1 frame builder ─────────────────────────────────────────────
// Decodes the JSON payload (produced by TelemetryBuilder) and re-encodes it as
// the compact VGPP-1 binary format for LoRaWAN uplink.

size_t LoRaWanClient::buildBinaryFrame(const char* jsonPayload, uint8_t* buf, size_t bufSize) {
    if (bufSize < VGPP_MAX_FRAME_LEN) return 0;

    StaticJsonDocument<512> doc;
    DeserializationError err = deserializeJson(doc, jsonPayload);
    if (err) {
        LOG_ERR(TAG, "JSON parse error: %s", err.c_str());
        return 0;
    }

    JsonObject sensors = doc["sensors"];
    JsonObject meta    = doc["meta"];
    if (sensors.isNull() || meta.isNull()) return 0;

    float soilPct  = sensors["soil_moisture_pct"]   | -1.0f;
    float soilTemp = sensors["soil_temp_c"]          | -999.0f;
    float atC      = sensors["ambient_temp_c"]       | -999.0f;
    float rh       = sensors["ambient_humidity_pct"] | -1.0f;
    float hpa      = sensors["pressure_hpa"]         | -1.0f;
    float lux      = sensors["light_lux"]            | -1.0f;
    float lwPct    = sensors["leaf_wetness_pct"]     | -1.0f;
    float battV    = meta["battery_voltage"]         | 0.0f;
    int   battPct  = meta["battery_pct"]             | 0;
    float solarV   = meta["solar_voltage"]           | -1.0f;
    bool  sensorOk = meta["sensor_ok"]               | true;

    // Build flags
    uint16_t flags = 0;
    if (soilPct  >= 0.0f)   flags |= FLAGS_SOIL_VALID;
    if (soilTemp > -900.0f) flags |= FLAGS_SOIL_TEMP_VALID;
    if (atC > -900.0f && rh >= 0.0f && hpa > 0.0f) flags |= FLAGS_BME280_VALID;
    if (lux >= 0.0f)        flags |= FLAGS_LUX_VALID;
    if (lwPct >= 0.0f)      flags |= FLAGS_LEAF_WETNESS_VALID;
    if (solarV >= 0.0f)     flags |= FLAGS_SOLAR_VALID;
    if (!sensorOk)          flags |= FLAGS_SENSOR_ERROR;
    if (battV < BATTERY_LOW_THRESHOLD_V && battV > 0.0f) flags |= FLAGS_LOW_BATTERY;

    static uint16_t seq = 0;
    size_t idx = 0;

    buf[idx++] = VGPP_PROTOCOL_V1;
    buf[idx++] = seq & 0xFF;
    buf[idx++] = (seq >> 8) & 0xFF;
    seq++;
    buf[idx++] = flags & 0xFF;
    buf[idx++] = (flags >> 8) & 0xFF;

    uint16_t soilX100 = (soilPct >= 0.0f) ? (uint16_t)(soilPct * 100.0f) : 0;
    buf[idx++] = soilX100 & 0xFF;
    buf[idx++] = (soilX100 >> 8) & 0xFF;

    uint16_t stEnc = (soilTemp > -900.0f) ? (uint16_t)((soilTemp + 40.0f) * 10.0f) : 0;
    buf[idx++] = stEnc & 0xFF;
    buf[idx++] = (stEnc >> 8) & 0xFF;

    uint16_t atEnc = (atC > -900.0f) ? (uint16_t)((atC + 40.0f) * 10.0f) : 0;
    buf[idx++] = atEnc & 0xFF;
    buf[idx++] = (atEnc >> 8) & 0xFF;

    uint16_t rhX100 = (rh >= 0.0f) ? (uint16_t)(rh * 100.0f) : 0;
    buf[idx++] = rhX100 & 0xFF;
    buf[idx++] = (rhX100 >> 8) & 0xFF;

    uint16_t hpaEnc = (hpa > 0.0f) ? (uint16_t)(hpa * 10.0f - 8500.0f) : 0;
    buf[idx++] = hpaEnc & 0xFF;
    buf[idx++] = (hpaEnc >> 8) & 0xFF;

    uint32_t luxU = (lux >= 0.0f) ? (uint32_t)lux : 0;
    buf[idx++] = luxU & 0xFF;
    buf[idx++] = (luxU >> 8) & 0xFF;
    buf[idx++] = (luxU >> 16) & 0xFF;

    buf[idx++] = (battV >= 0.0f) ? (uint8_t)(battV * 10.0f) : 0;
    buf[idx++] = (uint8_t)constrain(battPct, 0, 100);

    if (flags & FLAGS_LEAF_WETNESS_VALID) {
        uint16_t lwX100 = (uint16_t)(lwPct * 100.0f);
        buf[idx++] = lwX100 & 0xFF;
        buf[idx++] = (lwX100 >> 8) & 0xFF;
    }
    if (flags & FLAGS_SOLAR_VALID) {
        buf[idx++] = (uint8_t)(solarV * 10.0f);
    }

    uint16_t crc = Crc::crc16(buf, idx);
    buf[idx++] = crc & 0xFF;
    buf[idx++] = (crc >> 8) & 0xFF;

    return idx;
}
