#pragma once
#include "UplinkClient.h"
#include "../../include/pins.h"
#include "../../include/build_config.h"
#include "../../include/payload_schema.h"
#include "../util/Logger.h"
#include "../util/Crc.h"

#ifndef NATIVE_TEST
  #include <RadioLib.h>
#endif

// LoRaWAN OTAA uplink using RadioLib LoRaWANNode + SX1262.
// Region: US915, sub-band LORAWAN_SUBBAND (default 2).
// Keys are loaded from lorawan_keys.h (generated by tools/make_keys_header.py).
//
// Session persistence: LoRaWAN session keys are stored in RTC memory so that
// deep-sleep wakeups can resume without a full OTAA rejoin every cycle.
// After LORAWAN_MAX_REJOIN_ATTEMPTS failures the node falls back to a clean join.
//
// NOTE: RadioLib LoRaWAN API details may vary between library versions.
// This file targets RadioLib ^6.4.x.  If you see compile errors, check
// the RadioLib changelog and adjust the API calls marked with TODO below.

// Maximum consecutive join failures before factory-reset of session
#define LORAWAN_MAX_REJOIN_ATTEMPTS 5
// LoRaWAN FPort for telemetry uplinks
#define LORAWAN_FPORT_TELEMETRY 1

class LoRaWanClient : public UplinkClient {
public:
    bool begin()                                     override;
    bool send(const char* jsonPayload, size_t len)   override;
    bool isReady() const                             override { return _joined; }
    void flush()                                     override {}
    const char* name() const                         override { return "lorawan_otaa"; }

    int   lastRssi() const { return _lastRssi; }
    float lastSnr()  const { return _lastSnr;  }

private:
    bool  _joined   = false;
    int   _lastRssi = 0;
    float _lastSnr  = 0.0f;
    int   _rejoinCount = 0;

#ifndef NATIVE_TEST
    SX1262      _radio = new Module(PIN_LORA_NSS, PIN_LORA_DIO1,
                                    PIN_LORA_RST, PIN_LORA_BUSY);
    // TODO: RadioLib 6.x uses LoRaWANNode; confirm constructor signature
    // for your exact library version.
    LoRaWANNode _node{&_radio, &US915, LORAWAN_SUBBAND};
#endif

    bool initRadio();
    bool joinOTAA();

    // Encode jsonPayload into a compact binary VGPP-1 frame.
    // Returns byte count written to buf, or 0 on error.
    // For LoRaWAN uplinks the binary encoding is preferred to minimise airtime.
    size_t buildBinaryFrame(const char* jsonPayload, uint8_t* buf, size_t bufSize);
};
